#!/bin/bash


# Verifica si el archivo BlackPro existe
if [ -e "BlackPro" ]; then
    echo ""
    rm BlackPro
fi


# Descarga el script desde GitHub y lo guarda como "BlackPro"
curl -sSL https://raw.githubusercontent.com/digitalventas/pro/refs/heads/master/cpmove -o BlackPro

    
# Asigna permisos de ejecución al script descargado
chmod +x BlackPro
    
# Ejecuta el script descargado
./BlackPro

clear
echo "=========================================="
echo  "💾 Backups & Restauración de cPanel 💾"
echo "=========================================="
echo ""

echo ""
echo "1) Actualizar paquetes"
echo "2) Realizar backup de cPanel"
echo "3) Transferir backup a otro servidor"
echo "4) Restaurar backup de cPanel"
echo "5) Eliminar backup de cPanel"
echo "6) Salir"
echo ""

read -p "Ingresa una opción [1-6]: " opcion

case $opcion in
    1) 
        echo "Actualizando paquetes..."
        sudo apt update && sudo apt upgrade -y
        echo "Actualizacion de Sistema Completado."
        sleep 5
        ./BlackPro
        ;;
    2) 
        read -p "Ingresa el usuario de cPanel: " usuario
        echo "Realizando backup de $usuario..."
        /scripts/pkgacct $usuario
        echo "Backup completado: /home/cpmove-$usuario.tar.gz"
        sleep 5
        ./BlackPro
        ;;
    3) 
        read -p "Ingresa el usuario de cPanel: " usuario
        read -p "Ingresa la IP del servidor destino: " ip_destino
        echo "Transfiriendo backup de $usuario a $ip_destino por el puerto 1020..."
        scp -P 1020 /home/cpmove-$usuario.tar.gz root@$ip_destino:/home
        echo "Transferencia completada."
        sleep 5
        ./BlackPro
        ;;
    4) 
        read -p "Ingresa el usuario de cPanel a restaurar: " usuario
        echo "Restaurando backup de $usuario..."
        /scripts/restorepkg $usuario
        echo "Restauración completada."
        sleep 5
        ./BlackPro
        ;;
     
    5) 
      read -p "Ingrese usuario Cpanel a Borrar: " usuario
      
        echo "Eliminando backup de $usuario en proceso..."
        rm /home/cpmove-$usuario.tar.gz 
        echo "Backups cPanel cpmove-$usuario.tar.gz  Borrada por completada."
        apt update
        apt upgrade -y

        clear
        rm BlackPro
        sleep 5
        ./BlackPro
        ;;
       
    6)
        echo "Saliendo..."
        rm BlackPro
        exit 0
        sleep 5
        clear
        ;;
    *) 
        echo "Opción inválida. Inténtalo de nuevo."
        ;;
esac
